### ISSUE TITLE
Thank you sooo much!

### ISSUE THREAD

**Issue by johnb-xp** [theBoatman/fixing-signal#1]
I can't thank you enough for publishing these fixes.

Signal's battery usage went from 20%+ to less than 2%.

Do you know when these changes will be merged into the official Signal app? If not soon, will you be releasing a patched version of Signal 4.36?

**Comment by theBoatman** [comment]
Sorry for the late response - I didn't get a notification for your message...

Nice to hear that my little fix helps. Did you use fix8230.apk or sleepfix.apk?

 I just made a pull request to merge it into the repository. Lets hope it will be accepted, but I expect it to take some time.

I compiled and uploaded a new version of the sleepfix.apk yesterday.

**Comment by johnb-xp** [comment]
I'm using sleepfix.apk, and glad to see you've updated the apk again.
