### ISSUE TITLE
v4.41 build for sleepfix

### ISSUE THREAD

**Issue by starthal** [theBoatman/fixing-signal#2]
Thanks for all your work so far to provide these test builds! I would love a sleepfix build for the most recent release, 4.41 (to allow for backup migration from the unpatched version).

**Comment by five-c-d** [comment]
@starthal looks like @theBoatman skipped right from v4.40.1 and all the way to v4.42.2 ...which is the latest tagged-beta-channel-version from upstream (and likely to become 4.42.3 stable-channel this coming week methinks (<ins>edit: as of Monday 24th June greyson has pushed 4.42.3 into github.com/signalapp/Signal-Android but it is not yet in playStore</ins>)).  

Does that give you what you were wanting, in terms of ability to perform an encrypted backup-blob in the current stock version, and then import that backup-blob into the APK provided by theBoatman?  

p.s.  @theBoatman , I was planning/hoping to try and get a version of the rtSleep patchset into the sigX+sigGesT release which is currently 4.42.1-x1pre4 but in a couple days will probably become 4.42.3-x1 for test-pilots to hammer upon.  Are you interested in helping with that process, or at least, okay with me cherry-picking from your repos over into my personal area and then shoving something to @valldrac for Travis to build?  I don't have any enhancements to suggest, but I'd like to get a few more debuglogs collected to post into https://community.signalusers.org/t/call-for-testing-fixing-realtimesleeptimer-to-work-in-concurrent-threads/7189

**Comment by theBoatman** [comment]
Sorry for the late response - I had some really really really busy weeks and used the first free timeslot to just update to head and build whatever I got there :)

@starthal I hope the current build helps you. If you need a more specific version, then tell me and I will see whether I can provide it.

@five-c-d I am okay with everything that helps bringing this patch into production. I am glad if I can help, but at the moment I hadn't the time to read a single line of the sigX+sigGesT process and will need a few days to catch up.

**Comment by starthal** [comment]
@theBoatman that's perfect, thanks!
