### ISSUE TITLE
InstallFailed error

### ISSUE THREAD

**Issue by pled** [theBoatman/fixing-signal#4]
I tried to install Signal-website-universal-release-4.43.8-sleepfix.apk on my BQ Aquaris X Pro running LineageOS 16, but can't, installation failed. Here is the logcat.
[logcatSignalInstall.txt](https://github.com/theBoatman/fixing-signal/files/3501804/logcatSignalInstall.txt)
Thank you for trying to fix this issue (I can find RealtimeSleepTimer error in my logs with official Signal App, will be happy to try your fix if I can install it).

**Comment by theBoatman** [comment]
Hm, I can't see anything special at first sight in the logfile. Is any message shown on the screen? Have you verified after uninstalling the official version that it was removed successfully?

**Comment by pled** [comment]
Sorry, my log was useless. I tried install again, this log should be more interesting. 
[Logcat-Installation-Signal-RTSTE.txt](https://github.com/theBoatman/fixing-signal/files/3526233/Logcat-Installation-Signal-RTSTE.txt)
There is nothing else that "Application not installed" ending the installation process. 
![Screenshot_20190821-180359_Programme_d'installation_du_kit-small](https://user-images.githubusercontent.com/2879483/63449346-3bb24280-c440-11e9-8305-6a1badd17564.png)

I have to mention there is no microG or anything related to gapps on my phone (hope this is not the reason).
Thank you.

**Comment by pled** [comment]
REopen as closed by error. Good log is provided now.

**Comment by theBoatman** [comment]
Sorry I can't read anything useful out of the log. How did you trigger the install process? I usually use adb to install it.

**Comment by pled** [comment]
I install it from my file explorer (mixplorer), just like official signal apk. I downloaded latest apk 4.45-2, used adb to install it, and it worked fine ! :-D 
Will chek now if my battery usage is better with your apk ! crossing my fingers...
