### ISSUE TITLE
How to include the patch?

### ISSUE THREAD

**Issue by Eskuero** [theBoatman/fixing-signal#5]
Hello,
would you mind sharing which steps and modifications did you made to Signal-Android repository so it would build using https://github.com/signalapp/libsignal-service-java/pull/70 ?

As of now it will always pull the prebuilt library when building the .apk so no fixes include and I couldn't figure out how to exactly include libsignal-service-java in build.gradle as source.

Thanks in advance!

**Comment by theBoatman** [comment]
First you need to build the library locally with:

`gradlew.bat tasks installArchives`

And then you need to modify build.gradle of SignalAndroid and move mavenLocal() to the top of the repository list. Then it should pull the library from the local repository.

If this works you should get an error while compiling that the signature of the library is wrong. Then remove the signature from the list of signatures in build.gradle and now everything should run without error :)

**Comment by Eskuero** [comment]
Thanks!
I managed to follow your instructions successfully and had no trouble integrating them on my building setup so I'm closing this.

Two days after testing it's definetely better than it used to be. The RAM usage of the background process seems more stable as well. In the past I have seen it ramp up to more than 150MB but now is usually stable below 80MB.

For anyone interested I'm publishing it on my Fdroid's Nightly App Repo
https://repo.eskuero.me/
